# -*- coding: utf-8 -*-
"""jobsheet11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18efA36LuxCulyn6KoxPpCWkLWXyQrSdP
"""

def main():
  menu = ['Ayam Geprek','Ayam Penyet', 'Nasi Goreng', 'Nasi Briyani', 'Jus Alpukat', 'Jus Jeruk']
  
  repeat = 1
  data_pilih = []
  while True:
    print('\n\nMenu pilhan : ')
    print('--------------------------------')

    count = 1
    for data in menu:
      print('{}. {}'.format(count, data))
      count+=1
    print('0. Keluar')

    pilih_menu = eval(input('\nPilihan anda : '))
    data_pilih.append(menu[pilih_menu-1])
    
    print('\nMenu yang anda pilih adalah : {}'.format(menu[pilih_menu-1]))

    repeat = input('\nApakah anda mau memilih pesanan lagi (Y/N) : ')

    """menampilkan menu pilihan kemudian simpan di var data_pilih"""

    if repeat == 'n' or repeat == 'N' or repeat == 0:
        print('\n\nPesanan anda : ')

        for hasil in data_pilih:
          print(hasil)
              
        print('\nTerima kasih atas pesanannya.')

        break

    # """menampilkan data yang dipesan"""


try:
  main()
except Exception as error:
  print('Terjadi kesalahan')
  print(error)